### PR TITLE
Add code files

### PR DESCRIPTION
**Pull request by samuelazran**
Please review

[Review on Reviewable](https://reviewable.io/reviews/innovativetravel/auto-snapshot/1)

### CODE REVIEW

**Comment by bubenkoff** [comment]
Review status: 0 of 5 files reviewed at latest revision, 23 unresolved discussions.

---

*[auto_snapshot.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pR8Ca4Pc9EAi4sT-e:-K7pR8Ca4Pc9EAi4sT-f:472422813) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L1)):*
I would avoid the documentation in module docstring
instead you can document them all in README.rst in root

---

*[auto_snapshot.py, line 33 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pOe8BSn6YHeffC733:-K7pOe8CYROMTtlvCOVc:2032697162) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L33)):*
target to python3, why bother with python2 support?

---

*[auto_snapshot.py, line 36 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pOlGVneMC81oKCxwa:-K7pOlGVneMC81oKCxwb:-407510418) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L36)):*
sort imports: first python stdlib, then external dependencies, then local imports, all groups are alphasorted

---

*[auto_snapshot.py, line 39 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pP5Pa6xZ9cbGsacTQ:-K7pP5Pa6xZ9cbGsacTR:975478840) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L39)):*
that kind of import complicates the mocking
better import settings as modules

---

*[auto_snapshot.py, line 42 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPBHE_rggsJcQYo5l:-K7pPBHE_rggsJcQYo5m:-1824957564) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L42)):*
docstring, with documented params and return 
see example: http://stackoverflow.com/a/5339352

---

*[auto_snapshot.py, line 43 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPipW3pACpvAS4C4X:-K7pPipW3pACpvAS4C4Y:1089328316) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L43)):*
stick to double quotes, only use single quotes when you have double quotes in the string

---

*[auto_snapshot.py, line 53 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQ7oeklRQnwrxSSwY:-K7pQ7oeklRQnwrxSSwZ:-2074394107) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L53)):*
you could conditionally raise an exception and then you don't need 'else'
just return snapshots[0] 

---

*[auto_snapshot.py, line 60 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQKL90AqCtlxSWofE:-K7pQKL90AqCtlxSWofF:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L60)):*
docstring

---

*[auto_snapshot.py, line 76 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQLkbIVMBs7sS2uzn:-K7pQLkbIVMBs7sS2uzo:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L76)):*
docstring

---

*[auto_snapshot.py, line 122 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQc_Uomo74EpO2Asm:-K7pQc_Uomo74EpO2Asn:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L122)):*
docstring

---

*[auto_snapshot.py, line 136 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQgUUBcRwYfuItPF9:-K7pQgUUBcRwYfuItPFA:514258922) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L136)):*
docstring
also what's the point in having those params?

---

*[removal.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRIZseiZIlH_EMw9i:-K7pRIZseiZIlH_EMw9j:-1485100065) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L1)):*
the same about module documentation

---

*[removal.py, line 28 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRPIuA71fDfnAEOl5:-K7pRPIuA71fDfnAEOl6:-759707023) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L28)):*
sort imports

---

*[removal.py, line 35 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRKvcmT96W-sHCeuD:-K7pRKvcmT96W-sHCeuE:-485289920) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L35)):*
docstring, parameters not needed

---

*[settings.py, line 4 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRSthj0IvDm1wZMe2:-K7pRStiJhflUaWPh1-b:-170919595) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/settings.py#L4)):*
please use unix line endings
typo in the comment

---

*[tests/test_auto_snapshot.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRg2bxZEuK2U_bXjl:-K7pRg2bxZEuK2U_bXjm:-1914139700) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L1)):*
module docstring (but not the documentation)

---

*[tests/test_auto_snapshot.py, line 2 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRjbozp4FZPpUePiQ:-K7pRjbozp4FZPpUePiR:582848102) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L2)):*
don't use TestCase, but use mock

---

*[tests/test_auto_snapshot.py, line 20 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRoFdmSRpZWqPfv9S:-K7pRoFdmSRpZWqPfv9T:715680414) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L20)):*
with pytest runner no need in classes at all

---

*[tests/test_auto_snapshot.py, line 31 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRrtHraH_BIEkKD4H:-K7pRrtHraH_BIEkKD4I:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L31)):*
docstring

---

*[tests/test_auto_snapshot.py, line 47 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRtS57T_sPpe2m2uE:-K7pRtS6P2__3XJHXXcm:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L47)):*
docstring

---

*[utils.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRxSiSwrGq_fqIO-k:-K7pRxSjyyZkA9nBm_NS:2078357914) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/utils.py#L1)):*
module docstring

---

*[utils.py, line 3 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRylS6UJ2kA8n9HPm:-K7pRylS6UJ2kA8n9HPn:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/utils.py#L3)):*
docstring

---

*[utils.py, line 7 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pS07IlkzmR-2JjmRl:-K7pS07IlkzmR-2JjmRm:15916004) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/utils.py#L7)):*
docstring

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by bubenkoff** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[removal.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pRIZseiZIlH_EMw9i:-K7pRIZseiZIlH_EMw9j:-90502021) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L1)):*
the same a

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by bubenkoff** [comment]
Review status: 0 of 5 files reviewed at latest revision, 19 unresolved discussions.

---

*[removal.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUEZFXE-3MkH8Rn3q:-K7pUEZG4V1AN64xPjfJ:-1936867602) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L1)):*
the same about module docstring

---

*[removal.py, line 36 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUIulo_OMTC3fi3cG:-K7pUIulo_OMTC3fi3cH:874902116) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/removal.py#L36)):*
docstring, no parameters needed

---

*[tests/test_auto_snapshot.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUN3kJ8kJSJZ5J1pI:-K7pUN3kJ8kJSJZ5J1pJ:1687658940) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L1)):*
module docstring, sort imports and divide into groups

---

*[tests/test_auto_snapshot.py, line 2 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUb4Y-jTDNMCF4lsP:-K7pUb4Y-jTDNMCF4lsQ:-1384298266) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L2)):*
use mock, but don't use TestCase

---

*[tests/test_auto_snapshot.py, line 8 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUTVwYnKtNc1LkBLU:-K7pUTVwYnKtNc1LkBLV:-1121756082) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L8)):*
do not see any value in such class, especially declared in an old style
if those constants are used several times convert them to pytest fixtures
please also add tox.ini file to test the project with tox

---

*[tests/test_auto_snapshot.py, line 20 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUnZuiSf-G1kqGPz0:-K7pUnZuiSf-G1kqGPz1:-1021819169) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L20)):*
no need in classes with pytest - use functions

---

*[tests/test_auto_snapshot.py, line 31 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUrEM-TnBq9tSrCoV:-K7pUrEM-TnBq9tSrCoW:-1104688775) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L31)):*
docstrings for every test function

---

*[utils.py, line 1 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUtKyD4viJw-8Rxfi:-K7pUtKyD4viJw-8Rxfj:-760100259) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/utils.py#L1)):*
docstrings everywhere

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by bubenkoff** [comment]
please also add a Makefile with 'deploy' target which would upload the lambdas to aws using aws-cli

---

Review status: 0 of 5 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-:-K7pXthilolB-SHi7EfC:-710764338)*

**Comment by bubenkoff** [comment]
please also integrate the project with travis-ci and coveralls

---

Review status: 0 of 5 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-:-K7pk40k_fogNnuUWlDa:-594581663)*

**Comment by germangh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 19 unresolved discussions.

---

*[tests/test_auto_snapshot.py, line 8 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUTVwYnKtNc1LkBLU:-K7pyEHBd1fEGtkvsCZg:-1282699738) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L8)):*
Agree that there is no point in having this class. But why do you say it is declared in an old style? Because it doesn't explicitly inherit from `object`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by germangh** [comment]
I guess better to use codeship? No point in learning the ways of multiple CI providers.  An alternative maybe circleci which has one free container (it doesn't matter if it's a private repo). 

---

Review status: 0 of 5 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-:-K7qKoRT-Urja1DdezCA:925035468)*

**Comment by germangh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[auto_snapshot.py, line 43 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPipW3pACpvAS4C4X:-K7qb9RCUHcgffVrpFBo:165465478) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L43)):*
Is that a generally accepted convention? Some people (including myself) use single quotes for all strings except when they require interpolation, or when the string contains single quotes. I am fine with agreeing to using a common convention but I have to admin that using single quotes for dictionary keys looks slightly better to my eyes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by bubenkoff** [comment]
@germangh, this is opensource library (and note it's a simple library), so no need to use containerized builds (except that travis provides a builtin). And travis is like a standard for opensource already

---

Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[.gitignore, line 9 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xRbB0qfWFU9UB6F6u:-K7xRbB0qfWFU9UB6F6v:-1092891684) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/.gitignore#L9)):*
again windows line endings - please set up your ide to only use unix ones

---

*[auto_snapshot.py, line 33 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pOe8BSn6YHeffC733:-K7xRhXrQ8QXK9CrQlKq:-1574888770) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L33)):*
not addressed?

---

*[auto_snapshot.py, line 43 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPipW3pACpvAS4C4X:-K7xSnEhbJFCcs6TX-0s:-1711418729) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L43)):*
if you have ' in a string, which is not so rare, you have to use double quotes
also single quotes are not json-compartible
and, python stdlib is all doublequoted
the main issue is see here, is that @samuelazran has a mix of quotes without the reason

---

*[removal.py, line 48 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xTH3ZTUsWsUlJhSRH:-K7xTH3ZTUsWsUlJhSRI:352621163) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/removal.py#L48)):*
remove
instead, make this project a python package with setup.py
and create an entry point named say aws-lambda which will be a cli interface with subcommands for each operation

---

*[requirements-testing.txt, line 5 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xTfXL-RfvTq7lP5sL:-K7xTfXL-RfvTq7lP5sM:-510450427) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/requirements-testing.txt#L5)):*
line endings again

---

*[requirements.txt, line 1 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xThPfniXRB5yzjy84:-K7xThPfniXRB5yzjy85:677698165) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/requirements.txt#L1)):*
here

---

*[settings.py, line 4 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xTiA-DcVnTy_7MbKh:-K7xTiA-DcVnTy_7MbKi:677698165) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/settings.py#L4)):*
here

---

*[tests/test_auto_snapshot.py, line 8 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pUTVwYnKtNc1LkBLU:-K7xTzpri6_mwK73M7ha:1935787686) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/tests/test_auto_snapshot.py#L8)):*
for python3 only its not an issue, but for clarity i would still inherit from object

---

*[utils.py, line 2 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xU7pqcNhULXklSQDo:-K7xU7pqcNhULXklSQDp:-1682236634) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/utils.py#L2)):*
non pep257 compartible, check all the files

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-:-K7xR7tN1Zde1qh-NK21:708155141)*

**Comment by germangh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[auto_snapshot.py, line 33 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pOe8BSn6YHeffC733:-K7z259JaD06RguXN1aR:581825498) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L33)):*
AWS Lambda supports only Python 2.7 atm

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by germangh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[auto_snapshot.py, line 43 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPipW3pACpvAS4C4X:-K7z2FMtte9unFEd3fK4:819150451) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L43)):*
I see your points, thanks for clarifying

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by germangh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[removal.py, line 48 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xTH3ZTUsWsUlJhSRH:-K7z2wOJlESYr2ANxyIv:399207434) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/removal.py#L48)):*
Maybe an overkill for this small project, but whenever I need I a CLI with subcommands I really like the way click handles that: http://click.pocoo.org/6/quickstart/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by samuelazran** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[auto_snapshot.py, line 33 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pOe8BSn6YHeffC733:-K7qQQxSrdUcwgSN56jp:464166605) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L33)):*
amazon lambda service support only python 2.7

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by samuelazran** [comment]
*[auto_snapshot.py, line 136 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pQgUUBcRwYfuItPF9:-K83YusPimHsxSKnka7o:2092313718) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L136)):*
This handler is being called by aws, and those params are the event payload

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by samuelazran** [comment]
*[auto_snapshot.py, line 43 \[r1\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7pPipW3pACpvAS4C4X:-K83jvbxsgcMyY4BzClx:-1254604369) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/da60d8db8393929711ef8e0eced2048d7be18049/auto_snapshot.py#L43)):*
I used the convention of double quotes for natural text and for interpolation, single quotes  for anything that behaves like an identifier

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Comment by samuelazran** [comment]
*[removal.py, line 48 \[r2\]](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1#-K7xTH3ZTUsWsUlJhSRH:-K83r9qFOk2hFK_kSLxA:-1925334492) ([raw file](https://github.com/innovativetravel/auto-snapshot/blob/daf244a95ecf6f2295baa368fb1af236440f1170/removal.py#L48)):*
I use it to run the module locally. running tests will only use mocked services. No need for cli because the handler function is meant to be triggered via an external event such as cron job with no subcommands or params.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovativetravel/auto-snapshot/1)*

**Pull request merged**
